name: Java CD to AWS

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 with gitlab settings
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github
          settings-path: ${{ github.workspace }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Set project version
        env:
          GITHUB_REF: ${{ vars.GITHUB_REF }}
        run: chmod +x ./mvnw && ./mvnw versions:set -DnewVersion=release

      - name: Build with Apache Maven
        run: chmod +x ./mvnw && ./mvnw -s $GITHUB_WORKSPACE/settings.xml clean javadoc:jar source:jar package
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_KEYNAME: ${{ secrets.MAVEN_GPG_KEYNAME }}

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: jar-with-dependencies
          path: target/jack-en-poy-release-jar-with-dependencies.jar

  deploy:
    needs: build
    environment:
      name: production
    name: deploy
    runs-on: self-hosted
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: jar-with-dependencies
      # deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        env:
          GITHUB_REF: ${{ vars.GITHUB_REF }}
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: boring-jack-en-poy
          environment_name: production
          version_label: ${{ github.event.release.tag_name }}
          region: eu-north-1
          deployment_package: jack-en-poy-release-jar-with-dependencies.jar
          existing_bucket_name: elasticbeanstalk-eu-north-1-851725374612
          use_existing_version_if_available: true

  acceptance-test:
    needs: deploy
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Run acceptance tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: chmod +x ./mvnw && ./mvnw clean -f e2e-tests/pom.xml verify -DJACK_EN_POY_URL=http://jack-en-poy.eu-north-1.elasticbeanstalk.com

  smoke-test:
    needs: deploy
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Run smoke tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: curl -X GET http://jack-en-poy.eu-north-1.elasticbeanstalk.com/webapp/ -f
