name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Set project version
      env:
        GITHUB_REF: ${{ vars.GITHUB_REF }}
      run: chmod +x ./mvnw && ./mvnw versions:set -DnewVersion=stage

    - name: Run tests and publish analysis to sonarcloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: chmod +x ./mvnw && ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report -P coverage-per-test && ./mvnw sonar:sonar -P coverage-per-test -Dsonar.token=${SONAR_TOKEN}

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: jar-with-dependencies
        path: target/jack-en-poy-stage-jar-with-dependencies.jar

  deploy-to-stage:
    needs: build
    name: deploy
    runs-on: self-hosted
    environment:
      name: stage
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: jar-with-dependencies
      # deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: boring-jack-en-poy
          environment_name: jackenpoy-1
          version_label: ${{ github.SHA }}
          region: eu-north-1
          deployment_package: jack-en-poy-stage-jar-with-dependencies.jar
          existing_bucket_name: elasticbeanstalk-eu-north-1-851725374612

  acceptance-test:
    needs: deploy-to-stage
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Run acceptance tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: chmod +x ./mvnw && ./mvnw clean -f e2e-tests/pom.xml verify -DJACK_EN_POY_URL=http://jackenpoy.eu-north-1.elasticbeanstalk.com

  smoke-test:
    needs: deploy-to-stage
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Run smoke tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: curl -X GET http://jackenpoy.eu-north-1.elasticbeanstalk.com/webapp/ -f

